// EN + AR translations for the in-browser battle game (ported from legacy/translations/game.js).

export const gameEn: Record<string, string> = {
  PLAYER: 'PLAYER',
  BOSS: 'BOSS',
  SHIELD: 'SHIELD',
  BROKEN: 'BROKEN',
  'GO!': 'GO!',
  'GAME OVER': 'GAME OVER',
  'Press R to Restart': 'Press R to Restart',
  'VICTORY!': 'VICTORY!',
  'Press R to Play Again': 'Press R to Play Again',
  'SHIELD BREAK!': 'SHIELD BREAK!',
  BLOCKED: 'BLOCKED',
  BLOCK: 'BLOCK',
  'ENRAGED!': 'ENRAGED!',
  'DARK KNIGHT': 'DARK KNIGHT',
  'YOU DIED': 'YOU DIED',
  'PARRY!': 'PARRY!',
  'RIPOSTE!': 'RIPOSTE!',
  'GUARD BREAK!': 'GUARD BREAK!',
  Mobile: 'Mobile',
  Desktop: 'Desktop',
}

export const gameAr: Record<string, string> = {
  PLAYER: 'أنت',
  BOSS: 'الزعيم',
  SHIELD: 'الدرع',
  BROKEN: 'مكسور',
  'GO!': 'يلا!',
  'GAME OVER': 'انتهت اللعبة',
  'Press R to Restart': 'اضغط R عشان تعيد',
  'VICTORY!': 'فوز!',
  'Press R to Play Again': 'اضغط R عشان تلعب مرة ثانية',
  'SHIELD BREAK!': 'الدرع انكسر!',
  BLOCKED: 'مصدود',
  BLOCK: 'صد',
  'ENRAGED!': 'غاضب!',
  'DARK KNIGHT': 'الفارس المظلم',
  'YOU DIED': 'انتهيت',
  'PARRY!': 'صدّ!',
  'RIPOSTE!': 'هجوم مرتد!',
  'GUARD BREAK!': 'كسر الدفاع!',
  Mobile: 'جوال',
  Desktop: 'كمبيوتر',
}
